@baseUrl = http://localhost:3333
@now = {{$timestamp}}
@uid = {{$guid}}

### Registro (POST)
# @name register
POST {{baseUrl}}/api/registrar
Content-Type: application/json
Accept: application/json

{
  "nome": "Instituição de Teste",
  "cnpj": "12345678000294",
  "telefone": "11999991239",
  "email": "joao.silva11@example.com",
  "senha": "senha123",
  "descricao": "Instituição de Teste"
}


### (Opcional) Capturar ID retornado
@userId = {{register.response.body.$.id}}

### (Opcional) Buscar usuário recém-criado
GET {{baseUrl}}/users/{{userId}}
Accept: application/json
