version: "3.8"

services:
  app:
    build:
      context: .
      target: runner
    container_name: api_app_prod
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - /app/node_modules
    env_file:
      - .env.prod
    command: ["node", "dist/server.js"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - NODE_ENV=production

  db:
    image: postgres:14-alpine
    container_name: api_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
