version: "3.8"

services:
  app:
    build: .
    container_name: api_app
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
