version: "3.8"

services:
  app:
    build:
      context: .
      target: dev
    container_name: api_app_dev
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: ["sh", "/app/entrypoint.sh", "npm", "run", "dev"]
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: api_db_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
